<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0-windows10.0.18362.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <SupportedOSPlatformVersion>7.0</SupportedOSPlatformVersion>
        <Platforms>x64</Platforms>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x64'">
        <DebugType>embedded</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x64'">
        <DebugType>embedded</DebugType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Antelcat.I18N.SourceGenerators" Version="1.1.0"/>
        <PackageReference Include="SonarAnalyzer.CSharp" Version="10.27.0.140913">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Update="Nerdbank.GitVersioning">
          <Version>3.10.85</Version>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Strings.resx">
            <Generator>PublicResXFileCodeGenerator</Generator>
            <LastGenOutput>Strings.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <EmbeddedResource Update="Strings.zh-hans.resx">
            <DependentUpon>Strings.resx</DependentUpon>
        </EmbeddedResource>
        <EmbeddedResource Update="Strings.it.resx">
            <DependentUpon>Strings.resx</DependentUpon>
        </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Strings.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Strings.resx</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>
