//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BG3PakViewer.Locales {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BG3PakViewer.Locales.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Time:.
        /// </summary>
        public static string AboutDialogBuildTime {
            get {
                return ResourceManager.GetString("AboutDialogBuildTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS:.
        /// </summary>
        public static string AboutDialogOS {
            get {
                return ResourceManager.GetString("AboutDialogOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runtime:.
        /// </summary>
        public static string AboutDialogRuntime {
            get {
                return ResourceManager.GetString("AboutDialogRuntime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version:.
        /// </summary>
        public static string AboutDialogVersion {
            get {
                return ResourceManager.GetString("AboutDialogVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Files.
        /// </summary>
        public static string AllFiles {
            get {
                return ResourceManager.GetString("AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baldur&apos;s Gate 3 Package Viewer (Unofficial).
        /// </summary>
        public static string AppTitle {
            get {
                return ResourceManager.GetString("AppTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BMP Image.
        /// </summary>
        public static string BMPImage {
            get {
                return ResourceManager.GetString("BMPImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Export.
        /// </summary>
        public static string CancelExportOperationCaption {
            get {
                return ResourceManager.GetString("CancelExportOperationCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm to cancel the current export task?.
        /// </summary>
        public static string CancelExportOperationMessage {
            get {
                return ResourceManager.GetString("CancelExportOperationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DDS Image.
        /// </summary>
        public static string DDSImage {
            get {
                return ResourceManager.GetString("DDSImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default path for SaveFileDialog and SaveFolderDialog.
        /// </summary>
        public static string DefaultExportDirectoryDescription {
            get {
                return ResourceManager.GetString("DefaultExportDirectoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default Export Directory.
        /// </summary>
        public static string DefaultExportDirectoryHeader {
            get {
                return ResourceManager.GetString("DefaultExportDirectoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set default path for OpenFileDialog.
        /// </summary>
        public static string DefaultOpenDirectoryDescription {
            get {
                return ResourceManager.GetString("DefaultOpenDirectoryDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default open directory.
        /// </summary>
        public static string DefaultOpenDirectoryHeader {
            get {
                return ResourceManager.GetString("DefaultOpenDirectoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string Dependencies {
            get {
                return ResourceManager.GetString("Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory Settings.
        /// </summary>
        public static string DirectorySettingsHeader {
            get {
                return ResourceManager.GetString("DirectorySettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Completed.
        /// </summary>
        public static string ExportCompleted {
            get {
                return ResourceManager.GetString("ExportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Failed.
        /// </summary>
        public static string ExportFailedCaption {
            get {
                return ResourceManager.GetString("ExportFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to export the file. Please check the log for more details..
        /// </summary>
        public static string ExportFailedMessage {
            get {
                return ResourceManager.GetString("ExportFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Package.
        /// </summary>
        public static string ExportPakBtnLabel {
            get {
                return ResourceManager.GetString("ExportPakBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string FileLoadingDuplicateCaption {
            get {
                return ResourceManager.GetString("FileLoadingDuplicateCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File loading, please do not repeat the operation.
        /// </summary>
        public static string FileLoadingDuplicateMessage {
            get {
                return ResourceManager.GetString("FileLoadingDuplicateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is Not Supported To Preview..
        /// </summary>
        public static string FileNotSupportedPreviewMessage {
            get {
                return ResourceManager.GetString("FileNotSupportedPreviewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened File Not Found.
        /// </summary>
        public static string FileOpenedNoFoundCaption {
            get {
                return ResourceManager.GetString("FileOpenedNoFoundCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The opened file does not exist. Do you want to delete the associated record?.
        /// </summary>
        public static string FileOpenedNoFoundMessage {
            get {
                return ResourceManager.GetString("FileOpenedNoFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIF Image.
        /// </summary>
        public static string GIFImage {
            get {
                return ResourceManager.GetString("GIFImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GL Transmission Format.
        /// </summary>
        public static string GLTransmissionFormat {
            get {
                return ResourceManager.GetString("GLTransmissionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granny 3D File.
        /// </summary>
        public static string Granny3DFile {
            get {
                return ResourceManager.GetString("Granny3DFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Exporting.
        /// </summary>
        public static string IsExporting {
            get {
                return ResourceManager.GetString("IsExporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JPEG Image.
        /// </summary>
        public static string JPEGImage {
            get {
                return ResourceManager.GetString("JPEGImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the language for the application interface display.
        /// </summary>
        public static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string LanguageHelpText {
            get {
                return ResourceManager.GetString("LanguageHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Larian Resource File.
        /// </summary>
        public static string LarianResourceFile {
            get {
                return ResourceManager.GetString("LarianResourceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load resource.
        /// </summary>
        public static string LoadResourceFailed {
            get {
                return ResourceManager.GetString("LoadResourceFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level.
        /// </summary>
        public static string LogLevel {
            get {
                return ResourceManager.GetString("LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Message.
        /// </summary>
        public static string LogMessage {
            get {
                return ResourceManager.GetString("LogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Time.
        /// </summary>
        public static string LogTime {
            get {
                return ResourceManager.GetString("LogTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Tech DDS File is Not Supported To Preview..
        /// </summary>
        public static string LowTexDDSNotSupportedMessage {
            get {
                return ResourceManager.GetString("LowTexDDSNotSupportedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set the maximum number of lines to display in text preview.
        /// </summary>
        public static string MaxPreviewLinesDescription {
            get {
                return ResourceManager.GetString("MaxPreviewLinesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum Preview Lines.
        /// </summary>
        public static string MaxPreviewLinesHeader {
            get {
                return ResourceManager.GetString("MaxPreviewLinesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meshes.
        /// </summary>
        public static string Meshes {
            get {
                return ResourceManager.GetString("Meshes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previewing models without meshes is not supported.
        /// </summary>
        public static string ModelMissingMeshes {
            get {
                return ResourceManager.GetString("ModelMissingMeshes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software is already running.
        /// </summary>
        public static string MultipleInstanceCaption {
            get {
                return ResourceManager.GetString("MultipleInstanceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple instances may cause data to be overwritten incorrectly. Only single-instance operation is supported. Do you want to bring up the already open window?.
        /// </summary>
        public static string MultipleInstanceMessage {
            get {
                return ResourceManager.GetString("MultipleInstanceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opened Time.
        /// </summary>
        public static string OpenedTime {
            get {
                return ResourceManager.GetString("OpenedTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File Failed.
        /// </summary>
        public static string OpenFileFailedCaption {
            get {
                return ResourceManager.GetString("OpenFileFailedCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the file. The file may be corrupted or not a valid package..
        /// </summary>
        public static string OpenFileFailedMessage {
            get {
                return ResourceManager.GetString("OpenFileFailedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Package.
        /// </summary>
        public static string OpenPakBtnLabel {
            get {
                return ResourceManager.GetString("OpenPakBtnLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pak File.
        /// </summary>
        public static string PakFile {
            get {
                return ResourceManager.GetString("PakFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PNG Image.
        /// </summary>
        public static string PNGImage {
            get {
                return ResourceManager.GetString("PNGImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview Settings.
        /// </summary>
        public static string PreviewSettingHeader {
            get {
                return ResourceManager.GetString("PreviewSettingHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent.
        /// </summary>
        public static string Recent {
            get {
                return ResourceManager.GetString("Recent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open New File.
        /// </summary>
        public static string ReOpenFileCaption {
            get {
                return ResourceManager.GetString("ReOpenFileCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are currently browsing the pak file. Confirm to close the current one and open a new file?.
        /// </summary>
        public static string ReOpenFileMessage {
            get {
                return ResourceManager.GetString("ReOpenFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save file.
        /// </summary>
        public static string SaveFile {
            get {
                return ResourceManager.GetString("SaveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a Pak file.
        /// </summary>
        public static string SelectPak {
            get {
                return ResourceManager.GetString("SelectPak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIFF Image.
        /// </summary>
        public static string TIFFImage {
            get {
                return ResourceManager.GetString("TIFFImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpdateAvailable.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateBtnContent {
            get {
                return ResourceManager.GetString("UpdateBtnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Interface Settings.
        /// </summary>
        public static string UserInterfaceSettingsHeader {
            get {
                return ResourceManager.GetString("UserInterfaceSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorbis Audio File.
        /// </summary>
        public static string VorbisAudioFile {
            get {
                return ResourceManager.GetString("VorbisAudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Exporting.Are You Sure To Exit?.
        /// </summary>
        public static string WhenIsExportingExitMessage {
            get {
                return ResourceManager.GetString("WhenIsExportingExitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wwise Audio File.
        /// </summary>
        public static string WwiseAudioFile {
            get {
                return ResourceManager.GetString("WwiseAudioFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML File.
        /// </summary>
        public static string XmlFile {
            get {
                return ResourceManager.GetString("XmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom.
        /// </summary>
        public static string Zoom {
            get {
                return ResourceManager.GetString("Zoom", resourceCulture);
            }
        }
    }
}
